import { ProductDetails } from "@/types";

export const products: ProductDetails[] = [
  {
    _id: "sony-wh-1000xm6-2025",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    isFeatured: true,
    image: {
      publicId: "sony-wh-1000xm6",
      tiny: "/images/hero/sony-wh-1000xm6-2025.png",
      medium: "/images/hero/sony-wh-1000xm6-2025.png",
      large: "/images/hero/sony-wh-1000xm6-2025.png",
    },
    reviews: {
      avgRate: 0,
      roundAvgRate: 0,
      count: 0,
    },
    createdAt: "2025-05-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
    variant: {
      variation: "WH-1000XM6-White",
      sku: "SONY-WHM6-BLK",
      color: "White",
      inventory: 4200,
      globalPrice: 44900,
      salePrice: 40410,
      discountPercent: 10,
      saleStartDate: "2025-05-01T00:00:00Z",
      salePriceDecimal: "404.10",
      globalPriceDecimal: "449.00",
      isInStock: true,
    },
    modelName: "WH-1000XM6",
    description:
      "Sony's flagship wireless ANC headphones for 2025, with QN3 chip, 12-mic noise cancellation, Bluetooth 5.3, and premium build.",
    features: [
      "QN3 HD Noise Cancelling Processor",
      "Adaptive ANC optimized for voices & keyboard clatter",
      "Bluetooth 5.3 with SBC, AAC, LDAC & LC3 support",
      "Up to 32 h playback with ANC (≈40 h ANC off)",
      "360 Reality Audio support",
      "Upgraded folding earcups with slim travel case",
      "Environmental durability & repairable design",
    ],
    whatsInTheBox: [
      "WH-1000XM6 headphones",
      "USB-C to A charging cable",
      "Audio cable (3.5 mm)",
      "Carrying pouch",
      "Documentation & warranty",
    ],
    specifications: {
      Weight: "254 g",
      "Mic array": "12 microphones",
      Connectivity: "Bluetooth 5.3 (SBC/AAC/LDAC/LC3), multipoint",
      "Battery life": "≈32h (ANC on), ≈40h (ANC off)",
      "Quick charge": "10 min → 5 h playback",
      "ANC chip": "Sony QN3",
      "Noise sensors": "Adaptive call/mic optimization",
      "Sound formats": "360 Reality Audio, LDAC",
      Design: "Foldable earcups, recycled materials",
      Warranty: "1 year",
    },
    popularity: 0,
    salesCount: 0,
    visibility: true,
    subCategoryId: "headphones",
    categoryId: "electronics",
    __v: 0,
    id: "sony-wh-1000xm6-2025",
  },
  {
    _id: "samsung-galaxy-s25-ultra-2025",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    isFeatured: true,
    image: {
      publicId: "samsung-s25-ultra",
      tiny: "/images/hero/samsung-galaxy-s25-ultra-2025.png",
      medium: "/images/hero/samsung-galaxy-s25-ultra-2025.png",
      large: "/images/hero/samsung-galaxy-s25-ultra-2025.png",
    },
    reviews: {
      avgRate: 0,
      roundAvgRate: 0,
      count: 0,
    },
    createdAt: "2025-01-22T00:00:00Z",
    updatedAt: new Date().toISOString(),
    variant: {
      variation: "256 GB Titanium Black",
      sku: "SM-S25U-256-BLK",
      color: "Titan Black",
      inventory: 3500,
      globalPrice: 129900,
      salePrice: 116910,
      discountPercent: 10,
      saleStartDate: "2025-02-07T00:00:00Z",
      salePriceDecimal: "1169.10",
      globalPriceDecimal: "1299.00",
      isInStock: true,
    },
    modelName: "Galaxy S25 Ultra",
    description:
      "Samsung's premier 2025 flagship with titanium build, top-tier AI features, 200 MP camera, 6.9″ AMOLED display, S Pen support.",
    features: [
      "Snapdragon 8 Elite chipset (3 nm)",
      "6.9″ QHD+ AMOLED 2X with 120 Hz adaptive refresh",
      "AI enhancements: ProVisual Engine, Generative Edit, Audio Eraser",
      "200 MP main camera; dual telephoto (3x/5x optical , 100x Space Zoom)",
      "Embedded S Pen",
      "Up to 1 TB storage, 12 GB RAM",
      "5 000 mAh battery with 45 W charging",
      "7 years of Android and security updates",
    ],
    whatsInTheBox: [
      "Galaxy S25 Ultra",
      "USB-C to C cable",
      "SIM tool and documentation",
    ],
    specifications: {
      Dimensions: "77.6 x 162.8 x 8.2 mm",
      Weight: "≈218 g",
      OS: "Android 15, One UI 7",
      Display: "6.9″ QHD+ Dynamic AMOLED 2X, 120 Hz, 2600 nits",
      "Rear Camera":
        "200 MP wide + 50 MP ultrawide + 10 MP tele (5x) + 10 MP tele (3x)",
      "Front Camera": "12 MP, 4K/60, 8K/30",
      Battery: "5 000 mAh, 45 W wired, wireless & reverse charging",
      RAM: "12 GB",
      Storage: "256 GB (expandable none)",
      Chipset: "Snapdragon 8 Elite (3 nm)",
      Connectivity: "5G (sub-6/mmWave), Wi-Fi 7, UWB, NFC",
      "IP-Rating": "IP68",
    },
    popularity: 0,
    salesCount: 0,
    visibility: true,
    subCategoryId: "smartphones",
    categoryId: "electronics",
    __v: 0,
    id: "samsung-galaxy-s25-ultra-2025",
  },
  {
    _id: "apple-iphone-16e-2025",
    name: "iPhone 16e",
    brand: "Apple",
    isFeatured: true,
    image: {
      publicId: "apple-iphone-16e",
      tiny: "/images/hero/apple-iphone-16e-2025.png",
      medium: "/images/hero/apple-iphone-16e-2025.png",
      large: "/images/hero/apple-iphone-16e-2025.png",
    },
    reviews: {
      avgRate: 0,
      roundAvgRate: 0,
      count: 0,
    },
    createdAt: "2025-02-28T00:00:00Z",
    updatedAt: new Date().toISOString(),
    variant: {
      variation: "128 GB Black",
      sku: "IP16E-128-WHT",
      color: "Black",
      inventory: 5000,
      globalPrice: 59900,
      salePrice: 53910,
      discountPercent: 10,
      saleStartDate: "2025-02-28T00:00:00Z",
      salePriceDecimal: "539.10",
      globalPriceDecimal: "599.00",
      isInStock: true,
    },
    modelName: "iPhone 16e",
    description:
      "Entry-level iPhone in 2025, powered by A18 chip, OLED display, USB-C, single rear camera.",
    features: [
      "A18 chip",
      "6.1″ OLED display",
      "48 MP rear camera",
      "Face ID",
      "USB-C charging",
      "Action Button",
    ],
    whatsInTheBox: ["iPhone 16e", "USB-C to USB-C cable", "Documentation"],
    specifications: {
      Chipset: "Apple A18",
      RAM: "8 GB",
      "Rear Camera": "48 MP",
      "Front Camera": "12 MP",
      Display: "6.1 inch OLED",
      Storage: "128 GB",
      "Battery life": "≈12h video playback",
      Connectivity: "5G, Wi-Fi 6",
      Dimensions: "Similar to iPhone 16",
      Weight: "≈XXX g",
    },
    popularity: 0,
    salesCount: 0,
    visibility: true,
    subCategoryId: "smartphones",
    categoryId: "electronics",
    __v: 0,
    id: "apple-iphone-16e-2025",
  },
  {
    _id: "samsung-galaxy-watch-ultra-2025",
    name: "Galaxy Watch Ultra (2025)",
    brand: "Samsung",
    isFeatured: true,
    image: {
      publicId: "samsung-galaxy-watch-ultra-2025",
      tiny: "/images/hero/samsung-galaxy-watch-ultra-2025.png",
      medium: "/images/hero/samsung-galaxy-watch-ultra-2025.png",
      large: "/images/hero/samsung-galaxy-watch-ultra-2025.png",
    },
    reviews: {
      avgRate: 0,
      roundAvgRate: 0,
      count: 0,
    },
    createdAt: "2025-07-09T00:00:00Z",
    updatedAt: new Date().toISOString(),
    variant: {
      variation: "Titanium Blue 47 mm LTE",
      sku: "SM-WULTRA-47-LTE-TB",
      color: "Titanium Blue",
      inventory: 2000,
      globalPrice: 64900,
      salePrice: 58410,
      discountPercent: 10,
      saleStartDate: "2025-07-25T00:00:00Z",
      salePriceDecimal: "584.10",
      globalPriceDecimal: "649.00",
      isInStock: true,
    },
    modelName: "Galaxy Watch Ultra (2025)",
    description:
      "Samsung's new flagship smartwatch launched July 9, 2025—titanium case, rugged build, 64 GB storage, Gemini AI assistant and robust fitness-focused features.",
    features: [
      "47 mm titanium squircle case (Titanium Blue, Silver, White)",
      "1.5″ Super AMOLED display (480x480) with sapphire crystal",
      "Wear OS 6 with One UI 8 Watch",
      "Built-in Gemini AI assistant",
      "64 GB internal storage (≈50 GB usable)",
      "590 mAh battery, fast wireless charging",
      "Full LTE, GPS, NFC, Bluetooth 5.3",
      "Advanced health tools: Antioxidant Index, Running Coach",
      "Durable build: IP68 water-resistant, 10 ATM, MIL-STD-810H",
    ],
    whatsInTheBox: [
      "Galaxy Watch Ultra (2025)",
      "USB-C charging dock",
      "Extra strap",
      "Documentation & warranty",
    ],
    specifications: {
      "Case Size": "47 mm titanium",
      Weight: "≈60.5 g",
      Display: "1.5″ 480x480 Super AMOLED, 3 000 nits peak",
      Storage: "64 GB (≈50 GB usable)",
      Battery: "590 mAh",
      Chipset: "Exynos W1000 (3 nm)",
      Connectivity: "LTE, GPS (dual-band), Wi-Fi, NFC, Bluetooth 5.3",
      OS: "Wear OS 6 with One UI 8 Watch",
      Assistant: "Gemini AI",
      Durability: "10 ATM, IP68, MIL-STD-810H",
    },
    popularity: 0,
    salesCount: 0,
    visibility: true,
    subCategoryId: "smartwatches",
    categoryId: "electronics",
    __v: 0,
    id: "samsung-galaxy-watch-ultra-2025",
  },
];
