// This file is auto-generated from openapi.json
// Do not edit manually

export const routes = [
  { path: "/auth/register", methods: ["POST"] },
  { path: "/auth/login", methods: ["POST"] },
  { path: "/auth/refresh-token", methods: ["POST"] },
  { path: "/auth/verify-email", methods: ["POST"] },
  { path: "/auth/resend-verification-code", methods: ["POST"] },
  { path: "/auth/forgot-password", methods: ["POST"] },
  { path: "/auth/reset-password", methods: ["POST"] },
  { path: "/auth/google", methods: ["GET"] },
  { path: "/auth/logout", methods: ["DELETE"] },
  { path: "/carts/my", methods: ["GET", "POST"] },
  { path: "/carts/my/{productId}", methods: ["PATCH", "DELETE"] },
  { path: "/carts", methods: ["GET"] },
  { path: "/carts/{cartId}", methods: ["GET"] },
  { path: "/carts/{cartId}/items", methods: ["POST", "DELETE"] },
  {
    path: "/carts/{cartId}/items/{itemId}",
    methods: ["GET", "PATCH", "DELETE"],
  },
  { path: "/categories", methods: ["GET", "POST"] },
  { path: "/categories/{categoryId}", methods: ["GET", "PATCH", "DELETE"] },
  { path: "/categories/{categoryId}/subCategories", methods: ["GET", "POST"] },
  {
    path: "/categories/{categoryId}/subCategories/{subCategoryId}",
    methods: ["GET", "PATCH", "DELETE"],
  },
  { path: "/departments", methods: ["GET"] },
  { path: "/orders/my", methods: ["GET"] },
  { path: "/orders", methods: ["GET"] },
  { path: "/orders/{orderId}", methods: ["GET", "PATCH"] },
  { path: "/payments/checkout", methods: ["POST"] },
  { path: "/products", methods: ["GET", "POST"] },
  { path: "/products/recommended-products", methods: ["GET"] },
  { path: "/products/best-offers", methods: ["GET"] },
  { path: "/products/best-seller", methods: ["GET"] },
  { path: "/products/live-search", methods: ["GET"] },
  { path: "/products/product-filters", methods: ["GET"] },
  { path: "/products/{productId}", methods: ["GET", "PATCH", "DELETE"] },
  { path: "/products/{productId}/reviews", methods: ["GET", "POST"] },
  {
    path: "/products/{productId}/reviews/{reviewId}",
    methods: ["GET", "PATCH", "DELETE"],
  },
  { path: "/sales", methods: ["GET"] },
  { path: "/sales/{saleId}", methods: ["GET", "PATCH"] },
  { path: "/users/me", methods: ["GET", "PATCH"] },
  { path: "/users", methods: ["GET", "POST"] },
  { path: "/users/{userId}", methods: ["GET", "PATCH", "DELETE"] },
  { path: "/wishlists/my", methods: ["GET", "POST", "DELETE"] },
  { path: "/wishlists/my/{productId}", methods: ["DELETE"] },
  { path: "/wishlists", methods: ["GET", "DELETE"] },
  { path: "/wishlists/{wishlistId}", methods: ["GET", "POST", "DELETE"] },
];
